dropdown,input elements have been updated to grasp screenreaderconten…
Azure/cosmos-explorer pull request #1440
Opened 2023-04-21 14:06 UTC by MokireddySampath

…t for all the elements

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

2023-04-25 23:27 UTC, victor-meng commented on src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
> +              entityValueAriaLabel={attributeValueLabel}
The `attributeValueLabel` and `attributeNameLabel` are constants from `EntityTableHelper.tsx`. Why do you need to pass them via parameters? You can just import them from `EntityTableHelper.tsx`?

2023-04-25 23:29 UTC, victor-meng commented on src/Common/TableEntity.tsx
> +  const dropdownandlabelStyles: Partial<IDropdownStyles> = {
What's the purpose of this style?

2023-04-25 23:33 UTC, victor-meng requested changes
A second scrollbar appears in the panel now and there's extra spaces at the end.

![image](https://user-images.githubusercontent.com/56978073/234429520-e29589ec-1a73-4de7-ac64-178d442dffa3.png)

2023-04-25 23:47 UTC, victor-meng commented on src/Common/TableEntity.tsx
> +
Remove extra space

2023-09-05 23:18 UTC, vchske approved these changes

2023-09-22 21:22 UTC, jawelton74 approved these changes

2023-09-27 15:10 UTC, merged