[Query Copilot] Query Copilot button dropdown and shortcut
Azure/cosmos-explorer pull request #1582
Opened 2023-08-18 09:18 UTC by Klepic95

This pull request contains implementation related to Query Copilot buttons as well as enabling copilot to launch with ALT+C key.

Related tasks:
AB#2631874

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

2023-08-18 17:40 UTC, ato9000 requested changes
Please add a task to add unit tests for the keyboard events

2023-08-18 18:25 UTC, Klepic95 commented
> Please add a task to add unit tests for the keyboard events

Created: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2635830

2023-08-21 10:45 UTC, v-darkora submitted a review, later dismissed

2023-08-21 11:01 UTC, v-darkora approved these changes

2023-08-21 14:14 UTC, ato9000 approved these changes

2023-08-21 14:17 UTC, merged