Check for accounts that are restricted from connection string login.
Azure/cosmos-explorer pull request #1673
Opened 2023-10-20 18:46 UTC by jawelton74

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

This change adds a call to the portal backend to determine if an account has been restricted from connection string based login.
If account has been restricted, user is informed via an error tooltip.

2023-10-20 19:43 UTC, vchske requested changes

2023-10-20 19:43 UTC, vchske commented on src/Platform/Hosted/Components/ConnectExplorer.tsx
> +  window.document.getElementById("errorDetails").innerText = "";
You don't want to edit the DOM directly like this. If logic is self contained within a component, use state (like line 62) is the way to go. There are tons of examples throughout this repo's *.tsx files showing various React-native ways to alter the UI.

2023-10-20 20:13 UTC, vchske approved these changes

2023-10-20 23:25 UTC, sunghyunkang1111 submitted a review, later dismissed

2023-10-20 23:29 UTC, ato9000 submitted a review, later dismissed

2023-10-20 23:29 UTC, ato9000 commented on src/Platform/Hosted/Components/ConnectExplorer.tsx
>                  if (isResourceTokenConnectionString(connectionString)) {
we should probably also block resource tokens. These connection strings should also work to on if account is restricted

2023-10-23 18:41 UTC, vchske approved these changes

2023-10-23 18:57 UTC, sunghyunkang1111 approved these changes

2023-10-23 19:04 UTC, merged