Save splitter position and enable column selection in DocumentsTab
Azure/cosmos-explorer pull request #1881
Opened 2024-06-21 12:15 UTC by languy

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

2024-09-04 19:04 UTC, analogrelay requested changes
One non-blocking idea/thought. But the FluentProvider should be updated to use `CosmosFluentProvider` for consistency and avoid `height: 100%` in case we add tooltips/menus/etc. in the future.

2024-09-05 09:46 UTC, languy commented on src/Explorer/Panes/TableColumnSelectionPane/TableColumnSelectionPane.tsx
> +    <FluentProvider theme={theme} style={{ height: "100%" }}>
Agreed. Replaced `<FluentProvider>` with `<CosmosFluentProvider>` and moved the `height: 100%` out of the element (I had to put it as a new parent `<div>` has it has to fill up the parent's height and force `<CosmosFluentProvider>` to stretch using `display: flex`). I also double-checked that `<CosmosFluentProvider>` is not nested inside another `<CosmosFluentProvider>`.

2024-09-05 09:49 UTC, languy commented on src/Explorer/Panes/TableColumnSelectionPane/TableColumnSelectionPane.tsx
> +                label={`${columnDefinition.label}${columnDefinition.isPartitionKey ? " (partition key)" : ""}`}
Brilliant, thanks for the suggestion. This also made me realize I was using checkbox fluent v8 (which doesn't allow overriding the label slot), so I upgraded to v9, also cleaned up all styles to use `makeStyles` and removed the `.less` file.

2024-09-05 14:33 UTC, asierisayas approved these changes

2024-09-05 14:34 UTC, asierisayas approved these changes

2024-09-05 15:33 UTC, analogrelay approved these changes

2024-09-05 15:43 UTC, merged