GSI changes
Azure/cosmos-explorer pull request #1991
Opened 2024-10-07 13:55 UTC by ajparule

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

2025-03-28 15:23 UTC, jcocchi requested changes

2025-03-28 15:23 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "WarningBannerOnDelete": "After deprovisioning the Materializedviews Builder, your materializedviews will not be updated with new source changes anymore. Materializedviews builder is compute in y
Should this text refer to the "Global Secondary Index Builder" instead?

2025-03-28 15:23 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesBuilderDescription": "Provision a Globalsecondaryindexes builder cluster for your Azure Cosmos DB account. Globalsecondaryindexes builder is compute in your account that pe
Can you change the format of every "Globalsecondaryindexes" reference to have proper spacing? It should be "Global secondary indexes" with a space between each word

2025-03-29 16:19 UTC, ajparule commented
Test results
NoSql API
![image](https://github.com/user-attachments/assets/3da19556-92b1-46c3-be3a-8d457944df60)

Cassandra API
![image](https://github.com/user-attachments/assets/374fdeff-9cfb-48ea-a2b9-b73aefdd7a7f)

2025-03-31 05:14 UTC, ajparule commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesBuilderDescription": "Provision a Globalsecondaryindexes builder cluster for your Azure Cosmos DB account. Globalsecondaryindexes builder is compute in your account that pe
Updated

2025-03-31 05:15 UTC, ajparule commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "WarningBannerOnDelete": "After deprovisioning the Materializedviews Builder, your materializedviews will not be updated with new source changes anymore. Materializedviews builder is compute in y
Added GlobalsecondaryindexesWarningBannerOnDelete for GSI

2025-03-31 14:34 UTC, asier-isayas approved these changes

2025-03-31 15:04 UTC, jcocchi requested changes

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesDeleteMessage": "Global secondary indexes Builder resource is being deleted.",
```suggestion
    "GlobalsecondaryindexesDeleteMessage": "Global secondary indexes builder resource is being deleted.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesDeleteInitializeMessage": "Global secondary indexes Builder resource will be deleted.",
```suggestion
    "GlobalsecondaryindexesDeleteInitializeMessage": "Global secondary indexes builder resource will be deleted.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesDeleteSuccesseMessage": "Global secondary indexes Builder resource deleted.",
```suggestion
    "GlobalsecondaryindexesDeleteSuccesseMessage": "Global secondary indexes builder resource deleted.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesDeleteFailureMessage": "Global secondary indexes Builder resource deletion failed.",
```suggestion
    "GlobalsecondaryindexesDeleteFailureMessage": "Global secondary indexes builder resource deletion failed.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesCostText": "Hourly cost of the Global secondary indexes Builder resource depends on the SKU selection, number of instances per region, and number of regions.",
Is this true? I thought the builder was only ever provisioned in one region? Should we update this text?

```suggestion
    "GlobalsecondaryindexesCostText": "Hourly cost of the global secondary indexes builder resource depends on the SKU selection, number of instances per region, and number of regions.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesMetricsText": "Monitor the CPU and memory usage for the Global secondary indexes Builder instances in ",
```suggestion
    "GlobalsecondaryindexesMetricsText": "Monitor the CPU and memory usage for the global secondary indexes builder instances in ",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesResizingDecisionText": "To understand if the Global secondary indexes Builder is the right size, ",
```suggestion
    "GlobalsecondaryindexesResizingDecisionText": "To understand if the global secondary indexes builder is the right size, ",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesesizingDecisionLink": "learn more about Global secondary indexes Builder sizing.",
```suggestion
    "GlobalsecondaryindexesesizingDecisionLink": "learn more about global secondary indexes builder sizing.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesWarningBannerOnUpdate": "Adding or modifying Global secondary indexes Builder instances may affect your bill.",
```suggestion
    "GlobalsecondaryindexesWarningBannerOnUpdate": "Adding or modifying global secondary indexes builder instances may affect your bill.",
```

2025-03-31 15:04 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesWarningBannerOnDelete": "After deprovisioning the Global secondary indexes Builder, your Global secondary indexes will not be updated with new source changes anymore. Globa
```suggestion
    "GlobalsecondaryindexesWarningBannerOnDelete": "After deprovisioning the global secondary indexes builder, your global secondary indexes will no longer be updated with new source changes. Global secondary indexes builder is compute in your account that performs read operations on source collection for any updates and applies them on global secondary indexes as per their definition."
```

2025-04-02 17:16 UTC, jcocchi requested changes

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "MaterializedViewsBuilderDescription": "Provision a materialized views builder cluster for your Azure Cosmos DB account. Materialized views builder is compute in your account that performs read o
```suggestion
    "MaterializedViewsBuilderDescription": "Provision a materialized views builder for your Azure Cosmos DB account. Materialized views builder is compute in your account that performs read operations on source collection for any updates and applies them on materialized views as per the materialized view definition.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "MaterializedViewsBuilder": "Materialized views Builder",
```suggestion
    "MaterializedViewsBuilder": "Materialized views builder",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "CreateInitializeMessage": "Materialized views Builder resource will be provisioned.",
```suggestion
    "CreateInitializeMessage": "Materialized views builder resource will be provisioned.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "CreateFailureMessage": "Materialized views Builder resource provisioning failed.",
```suggestion
    "CreateFailureMessage": "Materialized views builder resource provisioning failed.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "UpdateSuccesseMessage": "Materialized views Builder resource updated.",
```suggestion
    "UpdateSuccesseMessage": "Materialized views builder resource updated.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "DeleteInitializeMessage": "Materialized views Builder resource will be deleted.",
```suggestion
    "DeleteInitializeMessage": "Materialized views builder resource will be deleted.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "DeleteSuccesseMessage": "Materialized views Builder resource deleted.",
```suggestion
    "DeleteSuccesseMessage": "Materialized views builder resource deleted.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "DeleteFailureMessage": "Materialized views Builder resource deletion failed.",
```suggestion
    "DeleteFailureMessage": "Materialized views builder resource deletion failed.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "CostText": "Hourly cost of the materialized views Builder resource depends on the SKU selection, number of instances per region, and number of regions.",
Is this true? I thought the builder was only provisioned in one region. So cost would only depend on SKU and number of nodes.

```suggestion
    "CostText": "Hourly cost of the materialized views builder resource depends on the SKU selection, number of instances per region, and number of regions.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "MetricsText": "Monitor the CPU and memory usage for the materialized views Builder instances in ",
```suggestion
    "MetricsText": "Monitor the CPU and memory usage for the materialized views builder instances in ",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "ResizingDecisionText": "To understand if the materialized views Builder is the right size, ",
```suggestion
    "ResizingDecisionText": "To understand if the materialized views builder is the right size, ",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "ResizingDecisionLink": "learn more about materialized views Builder sizing.",
```suggestion
    "ResizingDecisionLink": "learn more about materialized views builder sizing.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "WarningBannerOnUpdate": "Adding or modifying materialized views Builder instances may affect your bill.",
```suggestion
    "WarningBannerOnUpdate": "Adding or modifying materialized views builder instances may affect your bill.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "WarningBannerOnDelete": "After deprovisioning the materialized views Builder, your materialized views will not be updated with new source changes anymore. materialized views builder is compute i
```suggestion
    "WarningBannerOnDelete": "After deprovisioning the materialized views builder, your materialized views will not be updated with new source changes anymore. Materialized views builder is compute in your account that performs read operations on source containers for any updates and applies them on materialized views as per the materialized view definition.",
```

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesCostText": "Hourly cost of the global secondary indexes builder resource depends on the SKU selection, number of instances per region, and number of regions.",
Is this true? I thought it was one builder per account, not one per region

2025-04-02 17:16 UTC, jcocchi commented on src/Localization/en/MaterializedViewsBuilder.json
> +    "GlobalsecondaryindexesWarningBannerOnDelete": "After deprovisioning the global secondary indexes builder, your global secondary indexes will no longer be updated with new source changes. Global
```suggestion
    "GlobalsecondaryindexesWarningBannerOnDelete": "After deprovisioning the global secondary indexes builder, your global secondary indexes will no longer be updated with new source changes. Global secondary indexes builder is compute in your account that performs read operations on source containers for any updates and applies them on global secondary indexes as per their definition."
```

2025-04-03 17:52 UTC, jcocchi approved these changes
Looks like there are still a few unresolved comments but overall LGTM

2025-04-09 17:30 UTC, jawelton74 approved these changes

2025-04-09 17:32 UTC, merged