Add two filrs of Table to master
Azure/cosmos-explorer pull request #364
Opened 2021-01-04 23:50 UTC by Chris-MS-896

"./src/Explorer/Tables/DataTable/CacheBase.ts",
    "./src/Explorer/Tables/Entities.ts",

2021-01-05 19:04 UTC, ato9000 requested changes

2021-01-05 23:20 UTC, southpolesteve approved these changes

2021-01-07 23:29 UTC, Chris-MS-896 reviewed
all check pass

2021-01-09 00:40 UTC, ato9000 approved these changes

2021-01-09 02:57 UTC, merged