String input pane
Azure/cosmos-explorer pull request #678
Opened 2021-04-15 02:41 UTC by hardiknai-techm

2021-04-20 22:05 UTC, southpolesteve requested changes

2021-04-20 22:05 UTC, southpolesteve commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +    console.log("stringInput", stringInput);
Remove extra console.log

2021-04-20 22:05 UTC, southpolesteve commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +  const submit = () => {
Maybe this an async function

2021-04-20 22:05 UTC, southpolesteve commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +      .then((value: NotebookContentItem) => {
Use async/await

2021-04-23 13:55 UTC, hardiknai-techm commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +    console.log("stringInput", stringInput);
done

2021-04-24 03:52 UTC, hardiknai-techm commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +  const submit = () => {
yes, i have make async function

2021-04-24 03:53 UTC, hardiknai-techm commented on src/Explorer/Panes/StringInputPane/StringInputPane.tsx
> +      .then((value: NotebookContentItem) => {
done

2021-04-26 01:22 UTC, merged