Create End to End Graph Test
Azure/cosmos-explorer pull request #745
Opened 2021-05-04 11:52 UTC by hardiknai-techm

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)

2021-05-04 23:27 UTC, southpolesteve requested changes
You need to also add to the test name  to `ci.yml`under the e2e section so it gets run in CI.

2021-05-05 03:28 UTC, hardiknai-techm commented
added the test name to `ci.yml` under the e2e section

2021-05-05 03:29 UTC, hardiknai-techm commented
> 
> 
> You need to also add to the test name to `ci.yml`under the e2e section so it gets run in CI.

done

2021-05-05 04:00 UTC, southpolesteve approved these changes

2021-05-05 04:01 UTC, merged